services:
  gophersocial-postgres:
    image: postgres:16.3
    container_name: gophersocial-postgres
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  gophersocial-redis:
    image: redis:6.2-alpine
    container_name: gophersocial-redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis_data:/data

  gophersocial-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: gophersocial-redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    restart: always
    platform: linux/amd64
    depends_on:
      - gophersocial-redis
    environment:
      REDIS_HOST: gophersocial-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  db_data:
  redis_data: