services:
  gophersocial_postgres:
    image: postgres:16.3
    container_name: gophersocial_postgres
    environment:
      POSTGRES_USER: socialuser
      POSTGRES_PASSWORD: socialpassword
      POSTGRES_DB: gophersocial
    ports:
      - "5437:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: