basePath: /v1
info:
  contact:
    email: kenneth@addvanced.dk
    name: API Support
    url: http://www.swagger.io/support
  description: JWT Authorization header
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GopherSocial API
paths: {}
swagger: "2.0"
